In [57]:
import numpy as np

In [58]:
a=np.array([[[1,2,3,4,5],[2,3,4,5,9]],
           [[6,7,8,6,7],[6,7,8,6,6]]])

In [59]:
a.shape

(2, 2, 5)

In [60]:
a.astype

<function ndarray.astype>

In [61]:
a.size

20

In [62]:
a.strides

(40, 20, 4)

In [63]:
a.dtype

dtype('int32')

In [64]:
a.strides

(40, 20, 4)

In [81]:
a=np.array([1,2,3,4])
print(a)
print(a.T)

[1 2 3 4]
[1 2 3 4]


In [85]:
b=np.array([5,8,7,6])
print(b)

[5 8 7 6]


In [86]:
a*b

array([ 5, 16, 21, 24])

In [79]:
c=np.outer(a,b)
print(c)
print(c.T)

[[ 5  8  7  6  9]
 [10 16 14 12 18]
 [15 24 21 18 27]
 [20 32 28 24 36]]
[[ 5 10 15 20]
 [ 8 16 24 32]
 [ 7 14 21 28]
 [ 6 12 18 24]
 [ 9 18 27 36]]


In [83]:
np.dot(a,c)

array([150, 240, 210, 180, 270])

In [80]:
np.dot(c.T,a)

array([150, 240, 210, 180, 270])

In [23]:
c=np.ones((2,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
d=np.ones((4,5))
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
np.dot(a,b)

66

In [25]:
np.dot(c,d)

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [56]:
np.outer(a,b)

array([[ 5,  8,  7,  6],
       [10, 16, 14, 12],
       [15, 24, 21, 18],
       [20, 32, 28, 24]])

In [27]:
np.outer(b,a)

array([[ 5, 10, 15, 20],
       [ 8, 16, 24, 32],
       [ 7, 14, 21, 28],
       [ 6, 12, 18, 24]])

In [28]:
np.diag(a)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
np.array([a.T]*9).shape

(9, 4)

In [55]:
np.array([a]*9).T

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [35]:
b

array([5, 8, 7, 6])

In [36]:
a*b

array([ 5, 16, 21, 24])

In [37]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
a*c

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [39]:
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
e=np.random.rand(7,4)

In [47]:
print(e)

[[0.07748027 0.21196224 0.5779985  0.3683235 ]
 [0.89111876 0.72416742 0.86278142 0.8120337 ]
 [0.5512301  0.7277081  0.23040389 0.56965815]
 [0.02861939 0.48651174 0.45528548 0.4123838 ]
 [0.57804541 0.47066405 0.43133094 0.18949728]
 [0.35231273 0.25952885 0.95728361 0.58000654]
 [0.63388964 0.78697381 0.91791001 0.48535284]]


In [48]:
a*e

array([[0.07748027, 0.42392448, 1.73399549, 1.47329402],
       [0.89111876, 1.44833485, 2.58834427, 3.24813481],
       [0.5512301 , 1.4554162 , 0.69121167, 2.27863258],
       [0.02861939, 0.97302349, 1.36585643, 1.6495352 ],
       [0.57804541, 0.9413281 , 1.29399282, 0.75798914],
       [0.35231273, 0.51905771, 2.87185084, 2.32002615],
       [0.63388964, 1.57394762, 2.75373004, 1.94141136]])

In [ ]:
f=np.